version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: balance-app
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks:
      - balance-network

  nginx:
    image: nginx:latest
    container_name: balance-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - balance-network

networks:
  balance-network:
    driver: bridge