version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balance-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
        command: sh -c "chown -R www-data:www-data /var/www/data && php-fpm"
        # command: sh -c "chown -R www-data:www-data /var/www/data && php-fpm"
  
  nginx:
    image: nginx:alpine
    container_name: api_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app